/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.2 */

#ifndef PB_MESSAGES_PB_H_INCLUDED
#define PB_MESSAGES_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

#define PB_CONVERT_DOUBLE_FLOAT

/* Enum definitions */
typedef enum _Request_SSD1315Request_SetFont_Font {
    Request_SSD1315Request_SetFont_Font_u8x8_font_amstrad_cpc_extended_f = 0,
    Request_SSD1315Request_SetFont_Font_u8x8_font_5x7_f = 1,
    Request_SSD1315Request_SetFont_Font_u8x8_font_5x8_f = 2,
    Request_SSD1315Request_SetFont_Font_u8x8_font_8x13_1x2_f = 3,
    Request_SSD1315Request_SetFont_Font_u8x8_font_8x13B_1x2_f = 4,
    Request_SSD1315Request_SetFont_Font_u8x8_font_7x14_1x2_f = 5,
    Request_SSD1315Request_SetFont_Font_u8x8_font_7x14B_1x2_f = 6,
    Request_SSD1315Request_SetFont_Font_u8x8_font_open_iconic_arrow_1x1 = 7,
    Request_SSD1315Request_SetFont_Font_u8x8_font_open_iconic_check_1x1 = 8,
    Request_SSD1315Request_SetFont_Font_u8x8_font_open_iconic_embedded_1x1 = 9,
    Request_SSD1315Request_SetFont_Font_u8x8_font_open_iconic_play_1x1 = 10,
    Request_SSD1315Request_SetFont_Font_u8x8_font_open_iconic_thing_1x1 = 11,
    Request_SSD1315Request_SetFont_Font_u8x8_font_open_iconic_weather_1x1 = 12,
    Request_SSD1315Request_SetFont_Font_u8x8_font_open_iconic_arrow_2x2 = 13,
    Request_SSD1315Request_SetFont_Font_u8x8_font_open_iconic_check_2x2 = 14,
    Request_SSD1315Request_SetFont_Font_u8x8_font_open_iconic_embedded_2x2 = 15,
    Request_SSD1315Request_SetFont_Font_u8x8_font_open_iconic_play_2x2 = 16,
    Request_SSD1315Request_SetFont_Font_u8x8_font_open_iconic_thing_2x2 = 17,
    Request_SSD1315Request_SetFont_Font_u8x8_font_open_iconic_weather_2x2 = 18,
    Request_SSD1315Request_SetFont_Font_u8x8_font_open_iconic_arrow_4x4 = 19,
    Request_SSD1315Request_SetFont_Font_u8x8_font_open_iconic_check_4x4 = 20,
    Request_SSD1315Request_SetFont_Font_u8x8_font_open_iconic_embedded_4x4 = 21,
    Request_SSD1315Request_SetFont_Font_u8x8_font_open_iconic_play_4x4 = 22,
    Request_SSD1315Request_SetFont_Font_u8x8_font_open_iconic_thing_4x4 = 23,
    Request_SSD1315Request_SetFont_Font_u8x8_font_open_iconic_weather_4x4 = 24,
    Request_SSD1315Request_SetFont_Font_u8x8_font_open_iconic_arrow_8x8 = 25,
    Request_SSD1315Request_SetFont_Font_u8x8_font_open_iconic_check_8x8 = 26,
    Request_SSD1315Request_SetFont_Font_u8x8_font_open_iconic_embedded_8x8 = 27,
    Request_SSD1315Request_SetFont_Font_u8x8_font_open_iconic_play_8x8 = 28,
    Request_SSD1315Request_SetFont_Font_u8x8_font_open_iconic_thing_8x8 = 29,
    Request_SSD1315Request_SetFont_Font_u8x8_font_open_iconic_weather_8x8 = 30,
    Request_SSD1315Request_SetFont_Font_u8x8_font_profont29_2x3_f = 31,
    Request_SSD1315Request_SetFont_Font_u8x8_font_courB18_2x3_f = 32,
    Request_SSD1315Request_SetFont_Font_u8x8_font_courR18_2x3_f = 33,
    Request_SSD1315Request_SetFont_Font_u8x8_font_courB24_3x4_f = 34,
    Request_SSD1315Request_SetFont_Font_u8x8_font_courR24_3x4_f = 35,
    Request_SSD1315Request_SetFont_Font_u8x8_font_lucasarts_scumm_subtitle_o_2x2_f = 36,
    Request_SSD1315Request_SetFont_Font_u8x8_font_lucasarts_scumm_subtitle_r_2x2_f = 37,
    Request_SSD1315Request_SetFont_Font_u8x8_font_inr21_2x4_f = 38,
    Request_SSD1315Request_SetFont_Font_u8x8_font_inr33_3x6_f = 39,
    Request_SSD1315Request_SetFont_Font_u8x8_font_inr46_4x8_f = 40,
    Request_SSD1315Request_SetFont_Font_u8x8_font_inb21_2x4_f = 41,
    Request_SSD1315Request_SetFont_Font_u8x8_font_inb33_3x6_f = 42,
    Request_SSD1315Request_SetFont_Font_u8x8_font_inb46_4x8_f = 43,
    Request_SSD1315Request_SetFont_Font_u8x8_font_pressstart2p_f = 44,
    Request_SSD1315Request_SetFont_Font_u8x8_font_pcsenior_f = 45,
    Request_SSD1315Request_SetFont_Font_u8x8_font_pxplusibmcgathin_f = 46,
    Request_SSD1315Request_SetFont_Font_u8x8_font_pxplusibmcga_f = 47,
    Request_SSD1315Request_SetFont_Font_u8x8_font_pxplustandynewtv_f = 48,
    Request_SSD1315Request_SetFont_Font_u8x8_font_px437wyse700a_2x2_f = 49,
    Request_SSD1315Request_SetFont_Font_u8x8_font_px437wyse700b_2x2_f = 50
} Request_SSD1315Request_SetFont_Font;

/* Struct definitions */
typedef struct _Request_ConfigureRequest {
    pb_callback_t bme8280device;
    pb_callback_t hx711device;
    pb_callback_t ds18B20Device;
    pb_callback_t ssd1315Device;
} Request_ConfigureRequest;

typedef struct _Request_ResetRequest {
    char dummy_field;
} Request_ResetRequest;

typedef struct _Request_SSD1315Request_ClearDisplay {
    char dummy_field;
} Request_SSD1315Request_ClearDisplay;

typedef struct _Response_ErrorResponse {
    pb_callback_t text;
} Response_ErrorResponse;

typedef struct _Response_ResetResponse {
    char dummy_field;
} Response_ResetResponse;

typedef struct _Request_BME280Request {
    int32_t device;
} Request_BME280Request;

typedef struct _Request_ConfigureRequest_BME280Device {
    int32_t id;
} Request_ConfigureRequest_BME280Device;

typedef struct _Request_ConfigureRequest_DS18B20Device {
    int32_t id;
    int32_t pin;
} Request_ConfigureRequest_DS18B20Device;

typedef struct _Request_ConfigureRequest_HX711Device {
    int32_t id;
    int32_t doutPin;
    int32_t sckPin;
} Request_ConfigureRequest_HX711Device;

typedef struct _Request_ConfigureRequest_SSD1315Device {
    int32_t id;
} Request_ConfigureRequest_SSD1315Device;

typedef struct _Request_DS18B20Request {
    int32_t device;
} Request_DS18B20Request;

typedef struct _Request_HX711Request {
    int32_t device;
} Request_HX711Request;

typedef struct _Request_SSD1315Request_DrawString {
    int32_t x;
    int32_t y;
    pb_callback_t text;
} Request_SSD1315Request_DrawString;

typedef struct _Request_SSD1315Request_SetFont {
    Request_SSD1315Request_SetFont_Font font;
} Request_SSD1315Request_SetFont;

typedef struct _Response_BME280Response {
    int32_t pressure;
    int32_t temperature;
    int32_t humidity;
} Response_BME280Response;

typedef struct _Response_DS18B20Response {
    int32_t temperature;
} Response_DS18B20Response;

typedef struct _Response_HX711Response {
    double weight;
} Response_HX711Response;

typedef struct _Request_SSD1315Request {
    int32_t device;
    pb_size_t which_action;
    union {
        Request_SSD1315Request_ClearDisplay clearDisplay;
        Request_SSD1315Request_DrawString drawstring;
        Request_SSD1315Request_SetFont setFont;
    } action;
} Request_SSD1315Request;

typedef struct _Response {
    pb_size_t which_type;
    union {
        Response_ErrorResponse errorResponse;
        Response_ResetResponse resetResponse;
        Response_BME280Response bme280Response;
        Response_HX711Response hx711Response;
        Response_DS18B20Response ds18B20Response;
    } type;
} Response;

typedef struct _Request {
    pb_size_t which_type;
    union {
        Request_ResetRequest resetRequest;
        Request_ConfigureRequest configureRequest;
        Request_BME280Request bme280Request;
        Request_HX711Request hx711Request;
        Request_DS18B20Request dS18B20Request;
        Request_SSD1315Request ssd1315Request;
    } type;
} Request;


/* Helper constants for enums */
#define _Request_SSD1315Request_SetFont_Font_MIN Request_SSD1315Request_SetFont_Font_u8x8_font_amstrad_cpc_extended_f
#define _Request_SSD1315Request_SetFont_Font_MAX Request_SSD1315Request_SetFont_Font_u8x8_font_px437wyse700b_2x2_f
#define _Request_SSD1315Request_SetFont_Font_ARRAYSIZE ((Request_SSD1315Request_SetFont_Font)(Request_SSD1315Request_SetFont_Font_u8x8_font_px437wyse700b_2x2_f+1))


/* Initializer values for message structs */
#define Request_init_default                     {0, {Request_ResetRequest_init_default}}
#define Request_ResetRequest_init_default        {0}
#define Request_ConfigureRequest_init_default    {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define Request_ConfigureRequest_BME280Device_init_default {0}
#define Request_ConfigureRequest_HX711Device_init_default {0, 0, 0}
#define Request_ConfigureRequest_DS18B20Device_init_default {0, 0}
#define Request_ConfigureRequest_SSD1315Device_init_default {0}
#define Request_BME280Request_init_default       {0}
#define Request_HX711Request_init_default        {0}
#define Request_DS18B20Request_init_default      {0}
#define Request_SSD1315Request_init_default      {0, 0, {Request_SSD1315Request_ClearDisplay_init_default}}
#define Request_SSD1315Request_ClearDisplay_init_default {0}
#define Request_SSD1315Request_SetFont_init_default {_Request_SSD1315Request_SetFont_Font_MIN}
#define Request_SSD1315Request_DrawString_init_default {0, 0, {{NULL}, NULL}}
#define Response_init_default                    {0, {Response_ErrorResponse_init_default}}
#define Response_ResetResponse_init_default      {0}
#define Response_ErrorResponse_init_default      {{{NULL}, NULL}}
#define Response_BME280Response_init_default     {0, 0, 0}
#define Response_HX711Response_init_default      {0}
#define Response_DS18B20Response_init_default    {0}
#define Request_init_zero                        {0, {Request_ResetRequest_init_zero}}
#define Request_ResetRequest_init_zero           {0}
#define Request_ConfigureRequest_init_zero       {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define Request_ConfigureRequest_BME280Device_init_zero {0}
#define Request_ConfigureRequest_HX711Device_init_zero {0, 0, 0}
#define Request_ConfigureRequest_DS18B20Device_init_zero {0, 0}
#define Request_ConfigureRequest_SSD1315Device_init_zero {0}
#define Request_BME280Request_init_zero          {0}
#define Request_HX711Request_init_zero           {0}
#define Request_DS18B20Request_init_zero         {0}
#define Request_SSD1315Request_init_zero         {0, 0, {Request_SSD1315Request_ClearDisplay_init_zero}}
#define Request_SSD1315Request_ClearDisplay_init_zero {0}
#define Request_SSD1315Request_SetFont_init_zero {_Request_SSD1315Request_SetFont_Font_MIN}
#define Request_SSD1315Request_DrawString_init_zero {0, 0, {{NULL}, NULL}}
#define Response_init_zero                       {0, {Response_ErrorResponse_init_zero}}
#define Response_ResetResponse_init_zero         {0}
#define Response_ErrorResponse_init_zero         {{{NULL}, NULL}}
#define Response_BME280Response_init_zero        {0, 0, 0}
#define Response_HX711Response_init_zero         {0}
#define Response_DS18B20Response_init_zero       {0}

/* Field tags (for use in manual encoding/decoding) */
#define Request_ConfigureRequest_bme8280device_tag 1
#define Request_ConfigureRequest_hx711device_tag 2
#define Request_ConfigureRequest_ds18B20Device_tag 3
#define Request_ConfigureRequest_ssd1315Device_tag 4
#define Response_ErrorResponse_text_tag          1
#define Request_BME280Request_device_tag         1
#define Request_ConfigureRequest_BME280Device_id_tag 1
#define Request_ConfigureRequest_DS18B20Device_id_tag 1
#define Request_ConfigureRequest_DS18B20Device_pin_tag 2
#define Request_ConfigureRequest_HX711Device_id_tag 1
#define Request_ConfigureRequest_HX711Device_doutPin_tag 2
#define Request_ConfigureRequest_HX711Device_sckPin_tag 3
#define Request_ConfigureRequest_SSD1315Device_id_tag 1
#define Request_DS18B20Request_device_tag        1
#define Request_HX711Request_device_tag          1
#define Request_SSD1315Request_DrawString_x_tag  1
#define Request_SSD1315Request_DrawString_y_tag  2
#define Request_SSD1315Request_DrawString_text_tag 3
#define Request_SSD1315Request_SetFont_font_tag  1
#define Response_BME280Response_pressure_tag     1
#define Response_BME280Response_temperature_tag  2
#define Response_BME280Response_humidity_tag     3
#define Response_DS18B20Response_temperature_tag 1
#define Response_HX711Response_weight_tag        1
#define Request_SSD1315Request_device_tag        1
#define Request_SSD1315Request_clearDisplay_tag  2
#define Request_SSD1315Request_drawstring_tag    3
#define Request_SSD1315Request_setFont_tag       4
#define Response_errorResponse_tag               1
#define Response_resetResponse_tag               2
#define Response_bme280Response_tag              3
#define Response_hx711Response_tag               4
#define Response_ds18B20Response_tag             5
#define Request_resetRequest_tag                 1
#define Request_configureRequest_tag             2
#define Request_bme280Request_tag                3
#define Request_hx711Request_tag                 4
#define Request_dS18B20Request_tag               5
#define Request_ssd1315Request_tag               6

/* Struct field encoding specification for nanopb */
#define Request_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,resetRequest,type.resetRequest),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,configureRequest,type.configureRequest),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,bme280Request,type.bme280Request),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,hx711Request,type.hx711Request),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,dS18B20Request,type.dS18B20Request),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,ssd1315Request,type.ssd1315Request),   6)
#define Request_CALLBACK NULL
#define Request_DEFAULT NULL
#define Request_type_resetRequest_MSGTYPE Request_ResetRequest
#define Request_type_configureRequest_MSGTYPE Request_ConfigureRequest
#define Request_type_bme280Request_MSGTYPE Request_BME280Request
#define Request_type_hx711Request_MSGTYPE Request_HX711Request
#define Request_type_dS18B20Request_MSGTYPE Request_DS18B20Request
#define Request_type_ssd1315Request_MSGTYPE Request_SSD1315Request

#define Request_ResetRequest_FIELDLIST(X, a) \

#define Request_ResetRequest_CALLBACK NULL
#define Request_ResetRequest_DEFAULT NULL

#define Request_ConfigureRequest_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  bme8280device,     1) \
X(a, CALLBACK, REPEATED, MESSAGE,  hx711device,       2) \
X(a, CALLBACK, REPEATED, MESSAGE,  ds18B20Device,     3) \
X(a, CALLBACK, REPEATED, MESSAGE,  ssd1315Device,     4)
#define Request_ConfigureRequest_CALLBACK pb_default_field_callback
#define Request_ConfigureRequest_DEFAULT NULL
#define Request_ConfigureRequest_bme8280device_MSGTYPE Request_ConfigureRequest_BME280Device
#define Request_ConfigureRequest_hx711device_MSGTYPE Request_ConfigureRequest_HX711Device
#define Request_ConfigureRequest_ds18B20Device_MSGTYPE Request_ConfigureRequest_DS18B20Device
#define Request_ConfigureRequest_ssd1315Device_MSGTYPE Request_ConfigureRequest_SSD1315Device

#define Request_ConfigureRequest_BME280Device_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    id,                1)
#define Request_ConfigureRequest_BME280Device_CALLBACK NULL
#define Request_ConfigureRequest_BME280Device_DEFAULT NULL

#define Request_ConfigureRequest_HX711Device_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    id,                1) \
X(a, STATIC,   SINGULAR, INT32,    doutPin,           2) \
X(a, STATIC,   SINGULAR, INT32,    sckPin,            3)
#define Request_ConfigureRequest_HX711Device_CALLBACK NULL
#define Request_ConfigureRequest_HX711Device_DEFAULT NULL

#define Request_ConfigureRequest_DS18B20Device_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    id,                1) \
X(a, STATIC,   SINGULAR, INT32,    pin,               2)
#define Request_ConfigureRequest_DS18B20Device_CALLBACK NULL
#define Request_ConfigureRequest_DS18B20Device_DEFAULT NULL

#define Request_ConfigureRequest_SSD1315Device_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    id,                1)
#define Request_ConfigureRequest_SSD1315Device_CALLBACK NULL
#define Request_ConfigureRequest_SSD1315Device_DEFAULT NULL

#define Request_BME280Request_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    device,            1)
#define Request_BME280Request_CALLBACK NULL
#define Request_BME280Request_DEFAULT NULL

#define Request_HX711Request_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    device,            1)
#define Request_HX711Request_CALLBACK NULL
#define Request_HX711Request_DEFAULT NULL

#define Request_DS18B20Request_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    device,            1)
#define Request_DS18B20Request_CALLBACK NULL
#define Request_DS18B20Request_DEFAULT NULL

#define Request_SSD1315Request_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    device,            1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (action,clearDisplay,action.clearDisplay),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (action,drawstring,action.drawstring),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (action,setFont,action.setFont),   4)
#define Request_SSD1315Request_CALLBACK NULL
#define Request_SSD1315Request_DEFAULT NULL
#define Request_SSD1315Request_action_clearDisplay_MSGTYPE Request_SSD1315Request_ClearDisplay
#define Request_SSD1315Request_action_drawstring_MSGTYPE Request_SSD1315Request_DrawString
#define Request_SSD1315Request_action_setFont_MSGTYPE Request_SSD1315Request_SetFont

#define Request_SSD1315Request_ClearDisplay_FIELDLIST(X, a) \

#define Request_SSD1315Request_ClearDisplay_CALLBACK NULL
#define Request_SSD1315Request_ClearDisplay_DEFAULT NULL

#define Request_SSD1315Request_SetFont_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    font,              1)
#define Request_SSD1315Request_SetFont_CALLBACK NULL
#define Request_SSD1315Request_SetFont_DEFAULT NULL

#define Request_SSD1315Request_DrawString_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    x,                 1) \
X(a, STATIC,   SINGULAR, INT32,    y,                 2) \
X(a, CALLBACK, SINGULAR, STRING,   text,              3)
#define Request_SSD1315Request_DrawString_CALLBACK pb_default_field_callback
#define Request_SSD1315Request_DrawString_DEFAULT NULL

#define Response_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,errorResponse,type.errorResponse),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,resetResponse,type.resetResponse),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,bme280Response,type.bme280Response),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,hx711Response,type.hx711Response),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,ds18B20Response,type.ds18B20Response),   5)
#define Response_CALLBACK NULL
#define Response_DEFAULT NULL
#define Response_type_errorResponse_MSGTYPE Response_ErrorResponse
#define Response_type_resetResponse_MSGTYPE Response_ResetResponse
#define Response_type_bme280Response_MSGTYPE Response_BME280Response
#define Response_type_hx711Response_MSGTYPE Response_HX711Response
#define Response_type_ds18B20Response_MSGTYPE Response_DS18B20Response

#define Response_ResetResponse_FIELDLIST(X, a) \

#define Response_ResetResponse_CALLBACK NULL
#define Response_ResetResponse_DEFAULT NULL

#define Response_ErrorResponse_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   text,              1)
#define Response_ErrorResponse_CALLBACK pb_default_field_callback
#define Response_ErrorResponse_DEFAULT NULL

#define Response_BME280Response_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    pressure,          1) \
X(a, STATIC,   SINGULAR, SINT32,   temperature,       2) \
X(a, STATIC,   SINGULAR, INT32,    humidity,          3)
#define Response_BME280Response_CALLBACK NULL
#define Response_BME280Response_DEFAULT NULL

#define Response_HX711Response_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, DOUBLE,   weight,            1)
#define Response_HX711Response_CALLBACK NULL
#define Response_HX711Response_DEFAULT NULL

#define Response_DS18B20Response_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, SINT32,   temperature,       1)
#define Response_DS18B20Response_CALLBACK NULL
#define Response_DS18B20Response_DEFAULT NULL

extern const pb_msgdesc_t Request_msg;
extern const pb_msgdesc_t Request_ResetRequest_msg;
extern const pb_msgdesc_t Request_ConfigureRequest_msg;
extern const pb_msgdesc_t Request_ConfigureRequest_BME280Device_msg;
extern const pb_msgdesc_t Request_ConfigureRequest_HX711Device_msg;
extern const pb_msgdesc_t Request_ConfigureRequest_DS18B20Device_msg;
extern const pb_msgdesc_t Request_ConfigureRequest_SSD1315Device_msg;
extern const pb_msgdesc_t Request_BME280Request_msg;
extern const pb_msgdesc_t Request_HX711Request_msg;
extern const pb_msgdesc_t Request_DS18B20Request_msg;
extern const pb_msgdesc_t Request_SSD1315Request_msg;
extern const pb_msgdesc_t Request_SSD1315Request_ClearDisplay_msg;
extern const pb_msgdesc_t Request_SSD1315Request_SetFont_msg;
extern const pb_msgdesc_t Request_SSD1315Request_DrawString_msg;
extern const pb_msgdesc_t Response_msg;
extern const pb_msgdesc_t Response_ResetResponse_msg;
extern const pb_msgdesc_t Response_ErrorResponse_msg;
extern const pb_msgdesc_t Response_BME280Response_msg;
extern const pb_msgdesc_t Response_HX711Response_msg;
extern const pb_msgdesc_t Response_DS18B20Response_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Request_fields &Request_msg
#define Request_ResetRequest_fields &Request_ResetRequest_msg
#define Request_ConfigureRequest_fields &Request_ConfigureRequest_msg
#define Request_ConfigureRequest_BME280Device_fields &Request_ConfigureRequest_BME280Device_msg
#define Request_ConfigureRequest_HX711Device_fields &Request_ConfigureRequest_HX711Device_msg
#define Request_ConfigureRequest_DS18B20Device_fields &Request_ConfigureRequest_DS18B20Device_msg
#define Request_ConfigureRequest_SSD1315Device_fields &Request_ConfigureRequest_SSD1315Device_msg
#define Request_BME280Request_fields &Request_BME280Request_msg
#define Request_HX711Request_fields &Request_HX711Request_msg
#define Request_DS18B20Request_fields &Request_DS18B20Request_msg
#define Request_SSD1315Request_fields &Request_SSD1315Request_msg
#define Request_SSD1315Request_ClearDisplay_fields &Request_SSD1315Request_ClearDisplay_msg
#define Request_SSD1315Request_SetFont_fields &Request_SSD1315Request_SetFont_msg
#define Request_SSD1315Request_DrawString_fields &Request_SSD1315Request_DrawString_msg
#define Response_fields &Response_msg
#define Response_ResetResponse_fields &Response_ResetResponse_msg
#define Response_ErrorResponse_fields &Response_ErrorResponse_msg
#define Response_BME280Response_fields &Response_BME280Response_msg
#define Response_HX711Response_fields &Response_HX711Response_msg
#define Response_DS18B20Response_fields &Response_DS18B20Response_msg

/* Maximum encoded size of messages (where known) */
/* Request_size depends on runtime parameters */
#define Request_ResetRequest_size                0
/* Request_ConfigureRequest_size depends on runtime parameters */
#define Request_ConfigureRequest_BME280Device_size 11
#define Request_ConfigureRequest_HX711Device_size 33
#define Request_ConfigureRequest_DS18B20Device_size 22
#define Request_ConfigureRequest_SSD1315Device_size 11
#define Request_BME280Request_size               11
#define Request_HX711Request_size                11
#define Request_DS18B20Request_size              11
/* Request_SSD1315Request_size depends on runtime parameters */
#define Request_SSD1315Request_ClearDisplay_size 0
#define Request_SSD1315Request_SetFont_size      2
/* Request_SSD1315Request_DrawString_size depends on runtime parameters */
/* Response_size depends on runtime parameters */
#define Response_ResetResponse_size              0
/* Response_ErrorResponse_size depends on runtime parameters */
#define Response_BME280Response_size             28
#define Response_HX711Response_size              9
#define Response_DS18B20Response_size            6

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
