/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.2 */

#include "messages.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Request, Request, AUTO)


PB_BIND(Request_ResetRequest, Request_ResetRequest, AUTO)


PB_BIND(Request_ConfigureRequest, Request_ConfigureRequest, AUTO)


PB_BIND(Request_ConfigureRequest_BME280Device, Request_ConfigureRequest_BME280Device, AUTO)


PB_BIND(Request_ConfigureRequest_HX711Device, Request_ConfigureRequest_HX711Device, AUTO)


PB_BIND(Request_ConfigureRequest_DS18B20Device, Request_ConfigureRequest_DS18B20Device, AUTO)


PB_BIND(Request_ConfigureRequest_SSD1315Device, Request_ConfigureRequest_SSD1315Device, AUTO)


PB_BIND(Request_BME280Request, Request_BME280Request, AUTO)


PB_BIND(Request_HX711Request, Request_HX711Request, AUTO)


PB_BIND(Request_DS18B20Request, Request_DS18B20Request, AUTO)


PB_BIND(Request_SSD1315Request, Request_SSD1315Request, AUTO)


PB_BIND(Request_SSD1315Request_ClearDisplay, Request_SSD1315Request_ClearDisplay, AUTO)


PB_BIND(Request_SSD1315Request_SetFont, Request_SSD1315Request_SetFont, AUTO)


PB_BIND(Request_SSD1315Request_DrawString, Request_SSD1315Request_DrawString, AUTO)


PB_BIND(Response, Response, AUTO)


PB_BIND(Response_ResetResponse, Response_ResetResponse, AUTO)


PB_BIND(Response_ErrorResponse, Response_ErrorResponse, AUTO)


PB_BIND(Response_BME280Response, Response_BME280Response, AUTO)


PB_BIND(Response_HX711Response, Response_HX711Response, AUTO)


PB_BIND(Response_DS18B20Response, Response_DS18B20Response, AUTO)




#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif

